# Generated by Django 2.0.7 on 2019-02-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=10, verbose_name='学生姓名')),
                ('grade', models.SmallIntegerField(choices=[(1, '一年级'), (2, '二年级'), (3, '三年级'), (4, '四年级'), (5, '五年级'), (6, '六年级')], default=0, verbose_name='年级')),
                ('c_lass', models.SmallIntegerField(db_column='class', verbose_name='班级')),
                ('gender', models.SmallIntegerField(choices=[(0, '女性'), (1, '男性'), (2, 'others')], verbose_name='性别')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 't_students',
            },
        ),
    ]
