# Generated by Django 2.0.9 on 2020-06-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人信息')),
            ],
            options={
                'verbose_name': '表',
                'verbose_name_plural': '表',
                'db_table': 'test_table',
            },
        ),
    ]
