# Generated by Django 3.1.5 on 2021-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('state', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名称')),
                ('fname', models.CharField(blank=True, max_length=128, null=True, verbose_name='简称')),
            ],
            options={
                'verbose_name': '供应商表',
                'verbose_name_plural': '供应商表',
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人信息')),
            ],
            options={
                'verbose_name': '表',
                'verbose_name_plural': '表',
                'db_table': 'test_table',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('state', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
                ('file', models.FileField(upload_to='upload/', verbose_name='上传文件')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'files',
                'managed': True,
            },
        ),
    ]
