# Generated by Django 3.1.5 on 2021-02-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_temp',
            field=models.CharField(default=1, max_length=1024, verbose_name='文件路径'),
            preserve_default=False,
        ),
    ]
