# Generated by Django 2.0.9 on 2020-11-10 06:03

import apps.utils.model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScmWithErpSupplierRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('state', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
                ('account_book', models.SmallIntegerField(choices=[(1, '300'), (2, '400'), (3, '601')], verbose_name='ERP账套')),
                ('ven_code', models.CharField(max_length=20, verbose_name='账套中供应商Code')),
                ('ven_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='账套中供应商名称')),
                ('ven_abb_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='账套中供应商简称')),
            ],
            options={
                'verbose_name': '产能信息WaferSize标准表',
                'verbose_name_plural': '产能信息WaferSize标准表',
                'db_table': 'supplier_relations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('state', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名称')),
                ('fname', models.CharField(blank=True, max_length=128, null=True, verbose_name='简称')),
            ],
            options={
                'verbose_name': '产能信息WaferSize标准表',
                'verbose_name_plural': '产能信息WaferSize标准表',
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='scmwitherpsupplierrelations',
            name='supplier',
            field=apps.utils.model.VirtualForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test_model.Supplier', verbose_name='供应商'),
        ),
        migrations.AlterUniqueTogether(
            name='scmwitherpsupplierrelations',
            unique_together={('supplier', 'account_book', 'ven_code')},
        ),
    ]
