# Generated by Django 3.1.5 on 2021-02-24 10:08

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0002_uploadfile_file_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_icon',
            field=simplepro.components.fields.ImageField(default=1, max_length=128, verbose_name='图片上传'),
            preserve_default=False,
        ),
    ]
