# Generated by Django 2.0.9 on 2020-11-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0002_auto_20201110_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scmwitherpsupplierrelations',
            options={'managed': True, 'verbose_name': '供应商同ERP供应商关系表', 'verbose_name_plural': '供应商同ERP供应商关系表'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True, 'verbose_name': '供应商表', 'verbose_name_plural': '供应商表'},
        ),
    ]
