    # Generated by Django 2.0.9 on 2020-11-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0003_auto_20201110_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scmwitherpsupplierrelations',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scmwitherpsupplierrelations',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='ScmWithErpSupplierRelations',
        ),
    ]
