# Generated by Django 3.1.5 on 2021-02-26 03:34

from django.db import migrations
import simplecus.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0004_auto_20210225_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='category',
            field=simplecus.components.fields.CheckboxField(default=0, help_text='我是提示', max_length=12, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='int_input',
            field=simplecus.components.fields.InputNumberField(default=1, help_text='数字输入', verbose_name='InputNumber计数器'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='int_slide',
            field=simplecus.components.fields.SliderField(default=1, help_text='滑动改变数值', verbose_name='Slider滑块'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='isgood',
            field=simplecus.components.fields.SwitchField(default=False, help_text='点我切换', verbose_name='切换'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='point',
            field=simplecus.components.fields.RateField(default=0, verbose_name='评分2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='school',
            field=simplecus.components.fields.IntegerField(choices=[(0, '北大'), (1, '清华'), (2, '复旦'), (3, '交大'), (4, '厦大'), (5, '深大'), (6, '中山大学'), (7, '东南大学'), (8, '南开大学')], default=0, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='state',
            field=simplecus.components.fields.RadioField(choices=[(0, '无效'), (1, '有效')], default=0, help_text='继承自IntegerField', verbose_name='单选框'),
        ),
    ]
