# Generated by Django 3.1.5 on 2021-02-26 03:51

from django.db import migrations
import simplecus.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0006_auto_20210226_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_icon',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='create_time',
            field=simplecus.components.fields.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=simplecus.components.fields.RadioField(choices=[(0, '无效'), (1, '有效')], default=0, help_text='只能选一个', verbose_name='单选框'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='update_time',
            field=simplecus.components.fields.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
