# Generated by Django 3.1.5 on 2021-02-26 04:09

from django.db import migrations
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0007_auto_20210226_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='str_input',
            field=simplepro.components.fields.CharField(default='haha', max_length=128, verbose_name='输入框'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='supplier',
            field=simplepro.components.fields.ForeignKey(blank=True, help_text='选择一个人', null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_model.supplier'),
        ),
    ]
