# Generated by Django 3.1.5 on 2021-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0010_auto_20210323_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人信息')),
            ],
            options={
                'verbose_name': '表',
                'verbose_name_plural': '表',
                'db_table': 'test2_table',
                'managed': False,
            },
        ),
    ]
