# Generated by Django 2.0.9 on 2020-11-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1),
        ),
    ]
