# Generated by Django 3.1.5 on 2021-02-26 03:51

from django.db import migrations
import simplepro.components.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=simplepro.components.fields.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=simplepro.components.fields.RadioField(choices=[(0, '无效'), (1, '有效')], default=0, help_text='只能选一个', verbose_name='单选框'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=simplepro.components.fields.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
