# Generated by Django 2.1.2 on 2019-02-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190219_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号码'),
        ),
    ]
