# Generated by Django 3.1.5 on 2021-03-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDockingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_persistent', models.CharField(blank=True, max_length=200, null=True)),
                ('requested_at', models.DateTimeField(db_index=True)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(db_index=True, help_text='url path', max_length=200)),
                ('view', models.CharField(blank=True, db_index=True, help_text='method called by this endpoint', max_length=200, null=True)),
                ('view_method', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('host', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('query_params', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True, verbose_name='RequestId')),
                ('log_type', models.SmallIntegerField(choices=[(1, 'IN'), (2, 'OUT')], verbose_name='响应/请求')),
                ('device_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备型号')),
                ('device_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备名称')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP归属地址')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '接口对接日志记录表',
                'verbose_name_plural': '接口对接日志记录表',
                'db_table': 'log"."api_docking_log',
                'managed': True,
            },
        ),
    ]
