# Generated by Django 3.1.5 on 2021-03-23 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiDockingLog',
            new_name='RequestLog',
        ),
        migrations.AlterModelTable(
            name='requestlog',
            table='request_log',
        ),
    ]
