# Generated by Django 3.1.5 on 2021-03-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_log', '0002_auto_20210323_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'managed': True, 'verbose_name': '请求记录', 'verbose_name_plural': '请求记录'},
        ),
    ]
